- config: flags_test
  sourcecode: 
    - 'pvae/*.py'
    - exclude: "*.ipynb"
  flags:
    model: 'tree'
    manifold: 'PoincareBall'
    latent-dim: 2 
    hidden-dim: 200 
    prior-std: 1.7 
    c: 1.2 
    data-size: 50 
    dec: Wrapped 
    enc: Wrapped  
    prior: RiemannianNormal 
    posterior: RiemannianNormal 
    epochs: 1000 
    save-freq: 1000 
    lr: 1e-3 
    batch-size: 64 
    iwae-samples: 5000
    name: ''

- model : Test
  extends: flags_test 
  operations:
    synthetic:
        description: "A simple example from the authors"
        main: pvae/main
        flags-import: all
        flags:
            $include: flags_test
            data-params: [6 2 1 1 5 5 ]

    globins:
        description: "A simple example from the authors"
        main: pvae/main
        flags-import: all
        flags:
            $include: flags_test
            model: 'csv'
            data-param: 'globins'
            family: globins
            data-size: 3060
            epochs: 300
            prior: RiemannianNormal
            beta: 1.0
            learn-prior-std: False
            # posterior: WrappedNormal
            num-hidden-layers: 2
            lr: 1e-3
            # hidden-dim: 128
            # enc: Mob
            dec: Geo
            
          